### ISSUE TITLE
Android: Setup WebViews to utilize setUseWideViewPort

### ISSUE THREAD

**Issue by ImranSaadi** [warnerbros/cpe-manifest-android-experience#7]
## Summary
Enable wide view port for web-views to scale into web container. 

The flag to set the web view to use the viewport metadata is officially documented here: 
https://developer.android.com/reference/android/webkit/WebSettings.html#setUseWideViewPort(boolean)

Official documented for the web view can be found here: 
https://developer.android.com/reference/android/webkit/WebView.html

Here’s a code sample that sets the flag on the web view: 
```
WebView webView = findViewById(R.layout.NAME_OF_WEBVIEW); // NAME_OF_WEBVIEW is the name of the web view. An illustration on how to find NAME_OF_WEBVIEW is attached. 
webView.getSettings().setUseWideViewPort(true);
```

## JIRA
MAA-810

**Comment by gzcheng** [comment]
implemented
